//
//  SearchInteractor.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchInteractor: SearchInteractorInput {
    // MARK: - Properties
    weak var presenter: SearchInteractorOutput?
    
    // MARK: - SearchInteractorInput -

}
