//
//  SearchPresenter.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchPresenter {
    // MARK: - Properties
    weak private var view: SearchView?
    var interactor: SearchInteractorInput?
    private let router: SearchWireframeInterface

    // MARK: - Initialization and deinitialization -
    init(interface: SearchView, interactor: SearchInteractorInput?, router: SearchWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - SearchPresenterInterface -
extension SearchPresenter: SearchPresenterInterface {
    func navigateToFollowList(title: String) {
        self.router.navigate(to: .secondModule(title: title))
    }
}

// MARK: - SearchInteractorOutput -
extension SearchPresenter: SearchInteractorOutput {
    
}

