//
//  SearchViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class SearchViewController: UIViewController {
    // MARK: - Properties
	var presenter: SearchPresenterInterface?

    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .green
    }

}

// MARK: - SearchView
extension SearchViewController: SearchView {
    
}
