//
//  UserInfoViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 15.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class UserInfoViewController: UIViewController {
    // MARK: - Properties
	var presenter: UserInfoPresenterInterface?

    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .green
        presenter?.viewDidLoad()
    }

}

// MARK: - UserInfoView
extension UserInfoViewController: UserInfoView {
    
}
