//
//  UserInfoConfigurator.swift
//  GitHubFollowers
//
//  Created TOOK on 15.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct UserInfoConfigurator {

    static func createModule(with name: String) -> UIViewController {
        var view: UserInfoViewController!

        let viewController = UIStoryboard.init(name: "UserInfo", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in UserInfo.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as? UINavigationController)?.viewControllers.first as? UserInfoViewController
        } else {
            view = viewController as? UserInfoViewController
        }

        let interactor = UserInfoInteractor()
        let router = UserInfoRouter()
        let presenter = UserInfoPresenter(interface: view, interactor: interactor, router: router, name: name)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
