//
//  UserInfoInteractor.swift
//  GitHubFollowers
//
//  Created TOOK on 15.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class UserInfoInteractor: UserInfoInteractorInput {
    
    // MARK: - Properties
    weak var presenter: UserInfoInteractorOutput?
    
    // MARK: - UserInfoInteractorInput -
    func fetchData(userName: String) {
        FollowersSearchManager.searchUserInfo(name: userName)
        .done {[weak self] (userInfo) in
            self?.presenter?.fetchedUserInfo(userInfo: userInfo)
        }.catch {[weak self] (error) in
            self?.presenter?.fetchedUserInfo(error: error)
        }
        .finally {[weak self] in
            self?.presenter?.fetchedFully()
        }
    }
}
