//
//  UserInfoRouter.swift
//  GitHubFollowers
//
//  Created TOOK on 15.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class UserInfoRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - UserInfoWireframeInterface -
extension UserInfoRouter: UserInfoWireframeInterface {
    
    func navigate(to option: UserInfoNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
