//
//  FavouritesRouter.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class FavouritesRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - FavouritesWireframeInterface -
extension FavouritesRouter: FavouritesWireframeInterface {
    
    func navigate(to option: FavouritesNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
