//
//  FavouritesProtocols.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation

//MARK: Wireframe -
enum FavouritesNavigationOption {
    //    case firstModule
    //    case secondModule(someData)
}

protocol FavouritesWireframeInterface: class {
    func navigate(to option: FavouritesNavigationOption)
}

//MARK: Presenter -
protocol FavouritesPresenterInterface: class {

    var interactor: FavouritesInteractorInput? { get set }
    
    // MARK: - Lifecycle -
    func viewDidLoad()
    func viewWillAppear()
    func viewDidAppear()
    func viewWillDisappear()
    func viewDidDisappear()

}
extension FavouritesPresenterInterface {
    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewDidAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
    func viewDidDisappear() {/*leaves this empty*/}
}


//MARK: Interactor -
protocol FavouritesInteractorOutput: class {

    /* Interactor -> Presenter */
}

protocol FavouritesInteractorInput: class {

    var presenter: FavouritesInteractorOutput?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol FavouritesView: class {

    var presenter: FavouritesPresenterInterface?  { get set }

    /* Presenter -> ViewController */
}
