//
//  FavouritesPresenter.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class FavouritesPresenter {
    // MARK: - Properties
    weak private var view: FavouritesView?
    var interactor: FavouritesInteractorInput?
    private let router: FavouritesWireframeInterface

    // MARK: - Initialization and deinitialization -
    init(interface: FavouritesView, interactor: FavouritesInteractorInput?, router: FavouritesWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - FavouritesPresenterInterface -
extension FavouritesPresenter: FavouritesPresenterInterface {
    
}

// MARK: - FavouritesInteractorOutput -
extension FavouritesPresenter: FavouritesInteractorOutput {
    
}

