//
//  FavouritesViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 05.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class FavouritesViewController: UIViewController {
    // MARK: - Properties
	var presenter: FavouritesPresenterInterface?

    // MARK: - Lifecycle -
	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .brown
    }

}

// MARK: - FavouritesView
extension FavouritesViewController: FavouritesView {
    
}
