//
//  FollowerListViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 06.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import CollectionKit

class FollowerListViewController: UIViewController {
    // MARK: - Properties
    var presenter: FollowerListPresenterInterface?
    let collectionView = CollectionView()
    var cellsDataSource = ArrayDataSource<FollowerCell.Data>(data: [])
    private var isFetching: Bool = false
    
    
    // MARK: - Lifecycle -
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: true)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        configureCollection()
        presenter?.viewDidLoad()
    }
    
}

extension FollowerListViewController {
    private func configureCollection() {
        view.addSubview(collectionView)
        collectionView.backgroundColor = .systemBackground
        collectionView.fillSuperview()
        collectionView.alwaysBounceVertical = true
        collectionView.delaysContentTouches = false
        collectionView.delegate = self
        collectionView.provider = FollowerCellProvider(cellsDataSource)
        
    }
}

// MARK: - FollowerListView
extension FollowerListViewController: FollowerListView {
    func display(_ followersList: [FollowerCell.Data]) {
        cellsDataSource.data.append(contentsOf: followersList)
        collectionView.reloadData()
    }
}

extension FollowerListViewController {
    private func configureUI() {
        self.view.backgroundColor = .systemBackground
    }
}

extension FollowerListViewController: UIScrollViewDelegate {
    func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        let offsetY = scrollView.contentOffset.y
        let contentHeight = scrollView.contentSize.height
        if offsetY > contentHeight / 1.5 - scrollView.frame.height {
            if !isFetching {
                fetchingMore()
            }
        }
    }
    private func fetchingMore() {
        isFetching = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
            self.presenter?.fetchData()
            self.isFetching = false
        }
    }
}



