//
//  FollowerListViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 06.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class FollowerListViewController: UIViewController {
    // MARK: - Properties
    var presenter: FollowerListPresenterInterface?
    
    // MARK: - Lifecycle -
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.isNavigationBarHidden = false
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
    }
    
}

// MARK: - FollowerListView
extension FollowerListViewController: FollowerListView {
    
}

extension FollowerListViewController {
    private func configureUI() {
        self.view.backgroundColor = .systemBackground
    }
}


