//
//  FollowerListViewController.swift
//  GitHubFollowers
//
//  Created TOOK on 06.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit
import CollectionKit

class FollowerListViewController: UIViewController {
    // MARK: - Properties
    var presenter: FollowerListPresenterInterface?
    let collectionView = CollectionView()
    
    
    // MARK: - Lifecycle -
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: true)
        self.presenter?.viewWillAppear()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        configureCollection()
    }
    
}

extension FollowerListViewController {
    private func configureCollection() {
        view.addSubview(collectionView)
        collectionView.backgroundColor = .systemBackground
        collectionView.fillSuperview()
        collectionView.alwaysBounceVertical = true
        collectionView.delaysContentTouches = false
        
    }
}

// MARK: - FollowerListView
extension FollowerListViewController: FollowerListView {
    func display(_ followersList: [FollowerCell.Data]) {
        let dataSource = ArrayDataSource<FollowerCell.Data>.init(data: followersList) { (index, data) -> String in
            return "\(index)"
        }
        let provider = FollowerCellProvider(dataSource)
        collectionView.provider = provider
    }
}

extension FollowerListViewController {
    private func configureUI() {
        self.view.backgroundColor = .systemBackground
    }
}


